org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=1024M -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US
org.gradle.workers.max=2
org.gradle.parallel=false
kotlin.daemon.jvmargs=-Xmx768m
android.useAndroidX=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
